.\" Manpage vdown
.TH vdown 1 "04. September 2007"   
.SH NAME  
vdown \- Download videos from YouTube etc.
.SH SYNOPSIS  
\fBvdown\fP URL [ URL2 URL3 ... ]  
.SH DESCRIPTION  
\fIvdown\fP downloads videos from video sharing websites like YouTube, MySpace Video, Google Video, Clipfish and so on. 
The script uses <videograb.de>.
Videos will be saved as FLV file. 
.SH ERRORS 
Video sharing site may be not supported, link may be broken or ffmpeg may be not installed.
.SH BUGS
If you find a bug in vdown, please send an eMail to <nicolai@xeve.de>.
.SH AUTHOR
Nicolai Spohrer <nicolai@xeve.de>
.SH LICENSE
vdown is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.
.SH "SEE ALSO"
wget(1), sed(1), awk(1)
